### ISSUE TITLE
Create Login Widget for Authentication

### ISSUE THREAD

**Issue by thisisamurray** [astronomerio/public-api-houston-explorer#1]
Users should be able to provide a username and password in order to have the resulting token stored within their current session.

Needs:
- [x]  Username and password form fields with validation
- [x] Error reporting on response
- [x] Token storage within local storage, automatically log user in if present
- [x] Logout functionality, clear local storage token
- [ ] Style appropriately

**Comment by ryw** [comment]
@thisisamurray is this issue done/closable?

**Comment by thisisamurray** [comment]
It is still active.

**Comment by thisisamurray** [comment]
Will check progress tomorrow and update

**Comment by ryw** [comment]
Issue moved to [astronomerio/engineering #390](https://github.com/astronomerio/engineering/issues/390) via [**ZenHub**](https://www.zenhub.com/)
